
/**
 * @file overworld_map.h
 * DO NOT EDIT THIS FILE. PLEASE SEE THE README ON HOW TO EDIT THE MAP
 * THIS IS A GENERATED FILE
 */
#ifndef __OVERWORLD_MAP_H
#define __OVERWORLD_MAP_H

#include <libdragon.h>
#include <math.h>
#include "../utils.h"
#include "../Actor/npc.h"
#include "map.h"

npc_t overworldNpc1;

const int overworld_map_width = 8;
const int overworld_map_height = 10;
int overworld_bg_map[80] = {
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    0, 1, 2, 3, 4, 5, 6, 7, 
    
}; // All default to 0 / GRASS
int overworld_fg_map[80] = {
    8, 9, -1, -1, -1, -1, -1, -1, 
    16, 17, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, 12, 13, -1, -1, 
    -1, -1, -1, -1, 28, 29, -1, -1, 
    -1, -1, -1, -1, 20, 21, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, -1, 
    -1, -1, -1, -1, -1, -1, -1, 46, 
    
}; // All default to 0
npc_t *overworld_npcs[32] = {
    &overworldNpc1,
};
const uint8_t overworld_npcs_length = 1;

map_t overworld_map = {
    overworld_map_width,
    overworld_map_height,
    overworld_bg_map,
    overworld_fg_map,
    overworld_npcs,
    overworld_npcs_length,
};

#endif /* __OVERWORLD_MAP_H */
